---
title: "pigmentation_statistics"
output: html_document
---

```{r}
library(tidyverse)
library(lme4)
library(pixiedust)
library(kableExtra)
```

```{r}
data <- read.csv("full_pigmentation_removed.csv")
data <- data %>% mutate(log.Sum = log(Sum))
```


```{r}
model_comparisons <- data.frame(treatment=character(), time_gap=integer(), p=double())

for (t in unique(data$Treatment)) {
  time_gap = 1
  for (tps in list(c(3, 7), c(7, 9), c(9, 13))) {
    data_sub <- data %>% filter(TP %in% tps & Treatment == t)
    full.model = lmer(log.Sum ~ TP + (1|Experimenter) + (1|Sample), data=data_sub, REML=FALSE)
    noTP.model = lmer(log.Sum ~ (1|Experimenter) + (1|Sample), data=data_sub, REML=FALSE)
    p = anova(full.model, noTP.model)[2,8]
    model_comparisons <- rbind(model_comparisons, data.frame(treatment=c(t), time_gap=c(time_gap), p=c(p)))
    time_gap = time_gap + 1
  }
}

model_comparisons2 <- model_comparisons %>%
  mutate(
    time_gap = case_when(
      time_gap == 1 ~ "Jul 26 - Aug 25",
      time_gap == 2 ~ "Aug 25 - Sep 7",
      time_gap == 3 ~ "Sep 7 - Dec 22"
    ),
    p = case_when(
      p < 0.001 ~ "<0.001",
      p >= 0.001 ~ as.character(round(p, digits=3))
    ),
    sig = case_when(
      p < 0.05 ~ "*",
      p >= 0.001 ~ ""
    )
  )
```
```{r}
model_comparisons_treatment <- data.frame(TP=integer(), p=double())

for (tp in c(3, 7, 9, 13)) {
  data_sub <- data %>% filter(TP == tp)
  full.model = lmer(log.Sum ~ Treatment + (1|Experimenter) + (1|Sample), data=data_sub, REML=FALSE)
  noTreatment.model = lmer(log.Sum ~ (1|Experimenter) + (1|Sample), data=data_sub, REML=FALSE)
  p = anova(full.model, noTreatment.model)[2,8]
  model_comparisons_treatment <- rbind(model_comparisons_treatment, data.frame(TP=c(tp), p=c(p)))
}

model_comparisons_treatment2 <- model_comparisons_treatment %>%
  mutate(
    TP = case_when(
      TP == 3 ~ "Jul 26",
      TP == 7 ~ "Aug 25",
      TP == 9 ~ "Sep 7",
      TP == 13 ~ "Dec 22"
    ),
    p = case_when(
      p < 0.001 ~ "<0.001",
      p >= 0.001 ~ as.character(round(p, digits=3))
    ),
    sig = case_when(
      p < 0.05 ~ "*",
      p >= 0.001 ~ ""
    )
  )
```






--- PRACTICE / EXPERIMENTS BELOW ---

```{r}
model_comparisons_treatment <- data.frame(TP=integer(), p=double())

for (tp in c(3, 7, 9, 13)) {
  data_sub <- data %>% filter(TP == tp)
  pval = summary(aov(log.Sum~Treatment, data=data_sub))[[1]][["Pr(>F)"]][1]
  model_comparisons_treatment <- rbind(model_comparisons_treatment, data.frame(TP=c(tp), p=c(pval)))
}

```

```{r}
sum = summary(aov(log.Sum~Treatment, data=data))
sum[[1]][["Pr(>F)"]][1]
```

```{r}
full.model = lmer(log.Sum ~ Treatment + TP + Treatment*TP + (1|Experimenter) + (1|Sample), data=data, REML=FALSE)
```

```{r}
# TIME POINT
noTP.model = lmer(log.Sum ~ Treatment  + (1|Experimenter) + (1|Sample), data=data, REML=FALSE)
# noTP.model
comparison = anova(full.model, noTP.model)
comparison
```

```{r}
# TREATMENT
noTreatment.model = lmer(log.Sum ~ TP  + Treatment*TP + (1|Experimenter) + (1|Sample), data=data, REML=FALSE)
noTreatment.model
anova(full.model, noTreatment.model)
```

```{r}
# INTERACTION
noInteraction.model = lmer(log.Sum ~ TP + Treatment + (1|Experimenter) + (1|Sample), data=data, REML=FALSE)
noInteraction.model
anova(full.model, noInteraction.model)
```















```{r}
data <- read.csv("full_pigmentation_removed.csv")
data <- data %>% mutate(
  log.T5 = log(T5),
  log.T6 = log(T6),
  log.T7 = log(T7),
  log.Sum = log(Sum)
)

data[data == -Inf] <- 0
data_o1 <- data %>% filter(Experimenter == "Andy")
data_o2 <- data %>% filter(Experimenter == "Caitlynn")

observer_test <- data.frame(turgite=character(), observer1=character(), observer2=character(), tstat=double(), pval=double())

for (col in c("T5", "T6", "T7", "Sum")) {
  ttest = t.test(data_o1[col], data_o2[col])
  p = ttest$p.value
  t = ttest$statistic[["t"]]
  o1 = ttest$estimate[["mean of x"]]
  o2 = ttest$estimate[["mean of y"]]
  observer_test <- rbind(observer_test, data.frame(
    turgite=c(col),  observer1=c(o1), observer2=c(o2),tstat=c(t), pval=c(p))
    )
}


```


```{r}
dust(observer_test) %>% 
  sprinkle(col = 2, round = 3) %>% 
  sprinkle(col = 3, fn = quote(pvalString(pval))) %>% 
  sprinkle_colnames(
    turgite = "Turgite",
    tstat = "T Statistic",
    pval = "P-Value"
  ) %>% 
  kable() %>% 
  kable_styling()
```


