---
title: "pigmentation_visualization"
output: html_document
---

```{r}
library(tidyverse)
library(gridExtra)
```

```{r}
data <- read.csv("full_pigmentation_removed.csv")
data <- drop_na(data) 

pigmentation <- data %>% 
  group_by(TP, Treatment, Cage) %>% 
  summarise(
    mean_T5 = mean(T5),
    mean_T6 = mean(T6),
    mean_T7 = mean(T7),
    mean_Sum = mean(Sum)
  ) %>% 
  mutate(
    Cage = paste(Treatment, Cage, sep=""),
    TP = as.factor(TP),
    Treatment = case_when(
      Treatment == "E" ~ "Control",
      Treatment == "P" ~ "Experimental"
    )
  )

pigmentation_treament_mean <- read.csv("full_pigmentation_TP_treatment_nadrop2.csv")

pigmentation_treament_mean <- pigmentation_treament_mean %>% 
  mutate(
    TP = as.factor(TP),
    Treatment = case_when(
      Treatment == "E" ~ "Control",
      Treatment == "P" ~ "Experimental"
    )
  )
```

```{r}
pigmentation_treament_mean
```



```{r}
p1 <- ggplot(
  data=pigmentation,
  aes(x=TP, y=mean_T5, group=Treatment, color=Treatment)
) + 
geom_line(aes(group=Cage), alpha=0.2) +
geom_point(aes(color=Treatment), size= 0.2, alpha = 0.2) + 
geom_line(data=pigmentation_treament_mean, aes(x=TP, y=T5), size=1) +
geom_errorbar(data=pigmentation_treament_mean, aes(y=T5, ymin=T5-se5, ymax=T5+se5), width=.2,
               position=position_dodge(0.05))+
scale_color_manual(values=c("black","orange"))+
# scale_x_continuous(
#   breaks = c(3, 7, 9, 13), 
#   labels = c("Jul 26",  "Aug 25", "Sep 7", "Dec 22"),
#   ) +
scale_x_discrete(
  labels = c("Jul 26",  "Aug 25", "Sep 7", "Dec 22"),
) +
ylim(0, 10) +
labs( y = "T5 Pigmentation Score",  x="") +
theme_classic() +
theme(
  axis.title.x = element_text(size = 0),
  axis.title.y = element_text(size = 30),
  axis.text.x = element_text(size = 30),
  axis.text.y = element_text(size = 30),
  )  

p2 <- ggplot(
  data=pigmentation,
  aes(x=TP, y=mean_T6, group=Treatment, color=Treatment)
) + 
geom_line(aes(group=Cage), alpha=0.2) +
geom_point(aes(color=Treatment), size= 0.2, alpha = 0.2) + 
geom_line(data=pigmentation_treament_mean, aes(x=TP, y=T6), size=1) +
geom_errorbar(data=pigmentation_treament_mean, aes(y=T6, ymin=T6-se6, ymax=T6+se6), width=.2,
               position=position_dodge(0.05))+
scale_color_manual(values=c("black","orange"))+
# scale_x_continuous(
#   breaks = c(3, 7, 9, 13), 
#   labels = c("Jul 26",  "Aug 25", "Sep 7", "Dec 22"),
#   ) +
scale_x_discrete(
  labels = c("Jul 26",  "Aug 25", "Sep 7", "Dec 22"),
) +
ylim(0, 10) +
labs( y = "T6 Pigmentation Score",  x="") +
theme_classic() +
theme(
  axis.title.x = element_text(size = 0),
  axis.title.y = element_text(size = 30),
  axis.text.x = element_text(size = 30),
  axis.text.y = element_text(size = 30),
  )  

p3 <- ggplot(
  data=pigmentation,
  aes(x=TP, y=mean_T7, group=Treatment, color=Treatment)
) + 
geom_line(aes(group=Cage), alpha=0.2) +
geom_point(aes(color=Treatment), size= 0.2, alpha = 0.2) + 
geom_line(data=pigmentation_treament_mean, aes(x=TP, y=T7), size=1) +
geom_errorbar(data=pigmentation_treament_mean, aes(y=T7, ymin=T7-se7, ymax=T7+se7), width=.2,
               position=position_dodge(0.05))+
scale_color_manual(values=c("black","orange"))+
# scale_x_continuous(
#   breaks = c(3, 7, 9, 13), 
#   labels = c("Jul 26",  "Aug 25", "Sep 7", "Dec 22"),
#   ) +
scale_x_discrete(
  labels = c("Jul 26",  "Aug 25", "Sep 7", "Dec 22"),
) +
ylim(0, 10) +
labs( y = "T7 Pigmentation Score",  x="") +
theme_classic() +
theme(
  axis.title.x = element_text(size = 0),
  axis.title.y = element_text(size = 30),
  axis.text.x = element_text(size = 30),
  axis.text.y = element_text(size = 30),
  )  

p4 <- ggplot(
  data=pigmentation,
  aes(x=TP, y=mean_Sum, group=Treatment, color=Treatment)
) + 
geom_line(aes(group=Cage), alpha=0.2) +
geom_point(aes(color=Treatment), size= 0.2, alpha = 0.2) + 
geom_line(data=pigmentation_treament_mean, aes(x=TP, y=Sum), size=1) +
geom_point(data=pigmentation_treament_mean, aes(x=TP, y=Sum)) + 
geom_errorbar(data=pigmentation_treament_mean, aes(y=Sum, ymin=Sum-seSum, ymax=Sum+seSum), width=.2,     
              position=position_dodge(0.05))+
scale_color_manual(values=c("black","orange"))+
# scale_x_continuous(
#   breaks = c(3, 7, 9, 13), 
#   labels = c("Jul 26",  "Aug 25", "Sep 7", "Dec 22"),
#   ) +
scale_x_discrete(
  labels = c("Jul 26",  "Aug 25†", "Sep 7†", "Dec 22"),
) +
# ylim(0, 30) +
labs(y = "Sum Pigmentation Score",  x="") +
theme_classic() +
theme(
  axis.title.x = element_text(size = 0),
  axis.title.y = element_text(size = 28),
  axis.text.x = element_text(size = 30),
  axis.text.y = element_text(size = 30),
  legend.title = element_text(size = 30),
  legend.text = element_text(size = 25)
  )  

grid.arrange(p1, p2, p3, p4)
```


